parameters:
  - name: branch
    displayName: branch
    type: string
    default: 'main'

variables:
  - name: branch_name
    value: ${{ parameters.branch }}

resources:
  repositories:
  - repository: dynamic-checkout-repo2
    type: github
    ref: 'refs/heads/$(branch_name)'
    name: toddwalstad-eaton/dynamic-checkout-repo2
    endpoint: 'GitHub - toddwalstad-eaton'

stages:
  - stage: stage1
    jobs:
    - job: stage1job
      steps:
        - checkout: self
        - checkout: dynamic-checkout-repo2

